### ISSUE TITLE
[UI Bug] Sign-in page white space

### ISSUE THREAD

**Issue by mananpatel06** [horizon-ui/horizon-tailwind-react#9]
Bug details:-
White space at the end of Sign-in page.
For large-screen devices, website height is screen height, and that is the reason behind the bug.

Issue Recording 👇

https://github.com/user-attachments/assets/52f1357d-b9a9-4a8e-9c3e-055a4e6353cf

**Comment by simmmpleweb** [comment]
Fixed with [PR](https://github.com/horizon-ui/horizon-tailwind-react/pull/11)
